
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/Concordia University/Winter2025/Geometry/cmake-3.31.6-windows-x86_64/cmake-3.31.6-windows-x86_64/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.26100 - AMD64
...
